[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.123.3-a75a659f6fc0cb3a52b2b2ba666a81f79a459376+extended"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
